#!/usr/bin/env python3
"""Generate WAXDATA.SQL (INSERT statements) from the table in gen_data.py."""
import sys
sys.path.insert(0, ".")
import gen_data as g


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def main(out):
    lines = ["-- WAXDATA.SQL -- sample 80s collection (generated by gen_sql.py)",
             "-- Run after WAXDB.SQL:  SQL> ATTACH 'FILENAME WAXDB';  SQL> @WAXDATA", ""]
    aid = alb = hid = 0
    for name, origin, hair, albums in g.DATA:
        aid += 1
        lines.append("INSERT INTO ARTIST VALUES (%d, %s, %s, %d);" % (aid, q(name), q(origin), hair))
        for title, year, label, genre, holds in albums:
            alb += 1
            lines.append("INSERT INTO ALBUM VALUES (%d, %d, %s, %d, %s, %s);"
                         % (alb, aid, q(title), year, q(label), q(genre)))
            for media, grade, cents, bought, notes in holds:
                hid += 1
                lines.append("INSERT INTO HOLDING VALUES (%d, %d, %s, %s, %d, %d, %s);"
                             % (hid, alb, q(media), q(grade.strip()), cents, bought, q(notes)))
        lines.append("")
    lines.append("COMMIT;")
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %d artists, %d albums, %d holdings" % (out, aid, alb, hid))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "WAXDATA.SQL")
